# Generated by Django 2.0.13 on 2019-10-08 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attribute', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Attributes',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=50, unique=True)),
                ('Template', models.TextField(null=True)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ut.Classes')),
            ],
            options={
                'verbose_name': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='DataTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataType', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'DataTypes',
            },
        ),
        migrations.CreateModel(
            name='InputTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inputtype', models.CharField(max_length=50, unique=True)),
                ('HtmlLine', models.TextField(null=True)),
                ('Description', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'InputTypes',
            },
        ),
        migrations.CreateModel(
            name='Instances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=20)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ut.Classes')),
            ],
            options={
                'verbose_name': 'Instances',
            },
        ),
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_value', models.IntegerField(null=True)),
                ('char_value', models.CharField(max_length=255, null=True)),
                ('text_value', models.TextField(null=True)),
                ('float_value', models.FloatField(null=True)),
                ('datetime_value', models.DateTimeField(null=True)),
                ('Attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ut.Attributes')),
                ('Instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ut.Instances')),
                ('instance_value', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ut.Instances')),
            ],
            options={
                'verbose_name': 'Values',
            },
        ),
        migrations.AddField(
            model_name='attributes',
            name='Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ut.Classes'),
        ),
        migrations.AddField(
            model_name='attributes',
            name='DataType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ut.DataTypes'),
        ),
        migrations.AddField(
            model_name='attributes',
            name='InputType',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='ut.InputTypes'),
        ),
        migrations.AddField(
            model_name='attributes',
            name='Ref_Class',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ut.Classes'),
        ),
        migrations.AlterUniqueTogether(
            name='values',
            unique_together={('Instance', 'Attribute')},
        ),
        migrations.AlterUniqueTogether(
            name='instances',
            unique_together={('Class', 'Code')},
        ),
        migrations.AlterUniqueTogether(
            name='attributes',
            unique_together={('Class', 'Attribute')},
        ),
    ]
