# Generated by Django 2.0.13 on 2019-10-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='Filtered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attributes',
            name='ReadOnly',
            field=models.BooleanField(default=False),
        ),
    ]
