# Generated by Django 3.1.2 on 2021-05-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='DefaultValue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
