# Generated by Django 3.1.2 on 2021-05-03 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0002_attributes_defaultvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Values_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_value', models.FileField(null=True, upload_to='uploads/%Y/%m/%d/')),
                ('Attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ut.attributes')),
                ('Instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ut.instances')),
            ],
        ),
    ]
