# Generated by Django 3.1.2 on 2021-05-10 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0003_values_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='DefaultReport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ut.reports'),
        ),
        migrations.AlterField(
            model_name='values_files',
            name='file_value',
            field=models.FileField(null=True, upload_to='uploads/%Y%m%d%H%M%S'),
        ),
    ]
