# Generated by Django 3.1.2 on 2021-05-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ut', '0004_auto_20210509_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='UpdateGroups',
            field=models.ManyToManyField(blank=True, related_name='_projects_UpdateGroups_+', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='ViewGroups',
            field=models.ManyToManyField(blank=True, related_name='_projects_ViewGroups_+', to='auth.Group'),
        ),
    ]
