# Generated by Django 3.1.2 on 2021-05-15 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0005_auto_20210510_0609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputtypes',
            old_name='Inputtype',
            new_name='InputType',
        ),
    ]
