# Generated by Django 3.1.2 on 2021-05-18 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0006_auto_20210515_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Values_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_value', models.FileField(null=True, upload_to='uploads/%Y%m%d%H%M%S')),
                ('Attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ut.attributes')),
                ('Instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ut.instances')),
            ],
        ),
    ]
