# Generated by Django 3.1.2 on 2021-05-28 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0007_values_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='Parent',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ut.classes'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Values_images',
        ),
    ]
