# Generated by Django 3.1.2 on 2021-05-28 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0008_auto_20210528_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='Master',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='ut.classes'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='Parent',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ut.classes'),
        ),
    ]
