# Generated by Django 2.0.13 on 2019-10-14 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0008_auto_20191014_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributes',
            name='InternalUq',
        ),
        migrations.AddField(
            model_name='attributes',
            name='InternalAttribute',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ut.Attributes'),
        ),
    ]
