# Generated by Django 2.0.13 on 2019-10-16 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0009_auto_20191014_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='ExternalField',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='ExternalTable',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='ExternalUq',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='InputType',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, to='ut.InputTypes'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='Prefix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='Template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
