# Generated by Django 3.1.2 on 2021-07-02 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0009_auto_20210528_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplates',
            name='TemplateClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ut.classes'),
        ),
        migrations.AddField(
            model_name='emailtemplates',
            name='TemplateFilteredByClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ut.classes'),
        ),
    ]
