# Generated by Django 3.1.2 on 2021-07-04 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0010_auto_20210701_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplates',
            name='EmailField',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ut.attributes'),
        ),
    ]
