# Generated by Django 3.1.2 on 2021-07-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ut', '0011_emailtemplates_emailfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='OnDeleteEvent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='OnInsertEvent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='OnUpdateEvent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='UpdateGroups',
            field=models.ManyToManyField(blank=True, related_name='_attributes_UpdateGroups_+', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='ViewGroups',
            field=models.ManyToManyField(blank=True, related_name='_attributes_ViewGroups_+', to='auth.Group'),
        ),
    ]
