# Generated by Django 2.0.13 on 2019-11-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0011_layouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='UniqueAtt',
            field=models.BooleanField(default=False),
        ),
    ]
