# Generated by Django 2.2.5 on 2020-04-04 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0015_auto_20200105_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='instances',
            name='Master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ut.Instances'),
        ),
    ]
