# Generated by Django 2.2.5 on 2020-04-04 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0016_instances_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instances',
            name='Master',
        ),
    ]
