# Generated by Django 2.2.5 on 2020-05-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0017_remove_instances_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatypes',
            name='FieldFilter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datatypes',
            name='Filter1stName',
            field=models.CharField(default='min', max_length=50),
        ),
        migrations.AddField(
            model_name='datatypes',
            name='Filter2ndName',
            field=models.CharField(default='max', max_length=50),
        ),
    ]
