# Generated by Django 2.2.5 on 2020-07-12 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0020_projectclassconn_projectreportconn_projects_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectclassconn',
            name='Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ut.Classes'),
        ),
    ]
