# Generated by Django 3.1.2 on 2020-12-09 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0024_attributes_formula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Filter', models.CharField(max_length=50)),
                ('MinMax', models.BooleanField()),
                ('Condition1', models.CharField(max_length=50)),
                ('Condition2', models.CharField(max_length=50)),
                ('Condition3', models.CharField(max_length=50)),
                ('Formula', models.TextField()),
                ('Attribute1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ut.attributes')),
                ('Attribute2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ut.attributes')),
                ('Attribute3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ut.attributes')),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ut.classes')),
            ],
        ),
    ]
