# Generated by Django 3.1.2 on 2020-12-10 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0025_filters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filters',
            name='MinMax',
        ),
        migrations.AddField(
            model_name='filters',
            name='Min_and_Max',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filters',
            name='UseLike',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='filters',
            name='Attribute1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ut.attributes'),
        ),
        migrations.AlterField(
            model_name='filters',
            name='Attribute2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ut.attributes'),
        ),
        migrations.AlterField(
            model_name='filters',
            name='Attribute3',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ut.attributes'),
        ),
        migrations.AlterField(
            model_name='filters',
            name='Condition1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='filters',
            name='Condition2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='filters',
            name='Condition3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='filters',
            name='Formula',
            field=models.TextField(null=True),
        ),
    ]
