# Generated by Django 3.1.2 on 2020-12-10 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0026_auto_20201209_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filters',
            name='Condition1',
        ),
        migrations.RemoveField(
            model_name='filters',
            name='Condition2',
        ),
        migrations.RemoveField(
            model_name='filters',
            name='Condition3',
        ),
    ]
