# Generated by Django 3.1.2 on 2020-12-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0027_auto_20201209_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='filters',
            name='Condition1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='filters',
            name='Condition2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='filters',
            name='Condition3',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
