# Generated by Django 3.1.2 on 2020-12-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0028_auto_20201209_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='filters',
            name='Size',
            field=models.IntegerField(choices=[('col-sm-1', 1), ('col-sm-2', 2), ('col-sm-3', 3), ('col-sm-4', 4), ('col-sm-6', 6), ('col-sm-12', 12)], default=1),
        ),
        migrations.AlterField(
            model_name='filters',
            name='Condition1',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('AND', 'AND'), ('OR', 'OR')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='filters',
            name='Condition2',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('AND', 'AND'), ('OR', 'OR')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='filters',
            name='Condition3',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('AND', 'AND'), ('OR', 'OR')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='filters',
            name='Formula',
            field=models.TextField(blank=True, null=True),
        ),
    ]
