# Generated by Django 3.1.2 on 2020-12-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0029_auto_20201210_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filters',
            name='Min_and_Max',
        ),
        migrations.RemoveField(
            model_name='filters',
            name='UseLike',
        ),
        migrations.AddField(
            model_name='filters',
            name='FilterType',
            field=models.IntegerField(choices=[(1, 'Exact'), (2, 'Min and Max'), (3, 'Contain'), (4, 'SQL Style LIKE')], default=1),
        ),
    ]
