# Generated by Django 3.1.2 on 2020-12-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0030_auto_20201210_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filters',
            name='Condition3',
        ),
        migrations.AddField(
            model_name='values',
            name='manytomany',
            field=models.ManyToManyField(to='ut.Instances'),
        ),
        migrations.AlterField(
            model_name='filters',
            name='Condition1',
            field=models.CharField(blank=True, choices=[('OR', 'OR'), ('AND', 'AND')], default='OR', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='filters',
            name='Condition2',
            field=models.CharField(blank=True, choices=[('OR', 'OR'), ('AND', 'AND')], default='OR', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='filters',
            name='FilterType',
            field=models.IntegerField(choices=[(1, 'Exact'), (2, 'Min and Max'), (3, 'Contains'), (4, 'SQL Style LIKE')], default=1),
        ),
        migrations.AlterField(
            model_name='filters',
            name='Size',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (6, 6), (12, 12)], default=1),
        ),
    ]
