# Generated by Django 3.1.2 on 2020-12-20 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0031_auto_20201219_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Values_m2m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ut.attributes')),
                ('Instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ut.instances')),
                ('instance_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ut.instances')),
            ],
            options={
                'verbose_name': 'Values_m2m',
            },
        ),
    ]
