# Generated by Django 3.1.2 on 2020-12-20 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0032_values_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='values',
            name='manytomany',
        ),
    ]
