# Generated by Django 3.1.2 on 2020-12-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0033_remove_values_manytomany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectreportconn',
            name='Project',
        ),
        migrations.RemoveField(
            model_name='projectreportconn',
            name='Report',
        ),
        migrations.AddField(
            model_name='projects',
            name='Classes_m2m',
            field=models.ManyToManyField(null=True, to='ut.Classes'),
        ),
        migrations.AddField(
            model_name='projects',
            name='Reports_m2m',
            field=models.ManyToManyField(null=True, to='ut.Reports'),
        ),
        migrations.AlterUniqueTogether(
            name='values_m2m',
            unique_together={('Instance_id', 'Attribute_id', 'instance_value_id')},
        ),
        migrations.DeleteModel(
            name='ProjectClassConn',
        ),
        migrations.DeleteModel(
            name='ProjectReportConn',
        ),
    ]
