# Generated by Django 3.1.2 on 2020-12-21 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0034_auto_20201220_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='DefaultReport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ut.reports'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Classes_m2m',
            field=models.ManyToManyField(blank=True, to='ut.Classes'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Reports_m2m',
            field=models.ManyToManyField(blank=True, to='ut.Reports'),
        ),
    ]
