# Generated by Django 3.1.2 on 2020-12-22 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ut', '0035_auto_20201220_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='UpdateGroups',
            field=models.ManyToManyField(related_name='_attributes_UpdateGroups_+', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='attributes',
            name='ViewGroups',
            field=models.ManyToManyField(related_name='_attributes_ViewGroups_+', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='classes',
            name='UpdateGroups',
            field=models.ManyToManyField(related_name='_classes_UpdateGroups_+', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='classes',
            name='ViewGroups',
            field=models.ManyToManyField(related_name='_classes_ViewGroups_+', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='filters',
            name='UpdateGroups',
            field=models.ManyToManyField(related_name='_filters_UpdateGroups_+', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='filters',
            name='ViewGroups',
            field=models.ManyToManyField(related_name='_filters_ViewGroups_+', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='instances',
            name='Updated',
            field=models.DateTimeField(auto_now_add=True, default='2020-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instances',
            name='Updatedby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='UpdateGroups',
            field=models.ManyToManyField(related_name='_projects_UpdateGroups_+', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='projects',
            name='ViewGroups',
            field=models.ManyToManyField(related_name='_projects_ViewGroups_+', to='auth.Group'),
        ),
        migrations.AlterUniqueTogether(
            name='filters',
            unique_together={('Class', 'Filter')},
        ),
    ]
