# Generated by Django 3.1.2 on 2020-12-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0037_auto_20201230_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='instances',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, default='2020-01-01'),
            preserve_default=False,
        ),
    ]
