# Generated by Django 3.1.2 on 2021-01-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ut', '0038_instances_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='DeleteGroups',
            field=models.ManyToManyField(related_name='_classes_DeleteGroups_+', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='classes',
            name='InsertGroups',
            field=models.ManyToManyField(related_name='_classes_InsertGroups_+', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='classes',
            name='RighsFilteredByClass',
            field=models.ManyToManyField(related_name='_classes_RighsFilteredByClass_+', to='ut.Classes'),
        ),
    ]
