# Generated by Django 3.1.2 on 2021-01-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0039_auto_20210123_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='RighsFilteredByClass',
        ),
        migrations.AddField(
            model_name='classes',
            name='RightsFilteredByClass',
            field=models.ManyToManyField(related_name='_classes_RightsFilteredByClass_+', to='ut.Classes'),
        ),
    ]
