# Generated by Django 3.1.2 on 2021-02-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ut', '0040_auto_20210124_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatypes',
            name='FieldFilter',
        ),
        migrations.RemoveField(
            model_name='datatypes',
            name='Filter1stName',
        ),
        migrations.RemoveField(
            model_name='datatypes',
            name='Filter2ndName',
        ),
        migrations.AddField(
            model_name='classes',
            name='Class_query',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datatypes',
            name='FieldName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datatypes',
            name='InputTypes',
            field=models.ManyToManyField(blank=True, related_name='_datatypes_InputTypes_+', to='ut.InputTypes'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='DeleteGroups',
            field=models.ManyToManyField(blank=True, related_name='_classes_DeleteGroups_+', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='InsertGroups',
            field=models.ManyToManyField(blank=True, related_name='_classes_InsertGroups_+', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='RightsFilteredByClass',
            field=models.ManyToManyField(blank=True, related_name='_classes_RightsFilteredByClass_+', to='ut.Classes'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='UpdateGroups',
            field=models.ManyToManyField(blank=True, related_name='_classes_UpdateGroups_+', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='ViewGroups',
            field=models.ManyToManyField(blank=True, related_name='_classes_ViewGroups_+', to='auth.Group'),
        ),
    ]
