# Generated by Django 3.1.2 on 2021-02-16 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0041_auto_20210216_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='Calculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attributes',
            name='FT_Contains',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributes',
            name='FT_Exact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributes',
            name='FT_Like',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributes',
            name='FT_Max',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributes',
            name='FT_Min',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributes',
            name='LeftOuter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributes',
            name='MasterAttribute',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ut.attributes'),
        ),
        migrations.AddField(
            model_name='attributes',
            name='RefAttrTableName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attributes',
            name='RefTableName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attributes',
            name='SelectedField',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attributes',
            name='TableName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attributes',
            name='UseExternalTables',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attributes',
            name='ValueField',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attributes',
            name='ValueLeftOuter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
