# Generated by Django 3.1.2 on 2021-02-20 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0042_auto_20210216_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributes',
            name='Calculated',
        ),
        migrations.RemoveField(
            model_name='attributes',
            name='FT_Contains',
        ),
        migrations.RemoveField(
            model_name='attributes',
            name='FT_Exact',
        ),
        migrations.RemoveField(
            model_name='attributes',
            name='FT_Like',
        ),
        migrations.RemoveField(
            model_name='attributes',
            name='FT_Max',
        ),
        migrations.RemoveField(
            model_name='attributes',
            name='FT_Min',
        ),
        migrations.RemoveField(
            model_name='attributes',
            name='LeftOuter',
        ),
        migrations.RemoveField(
            model_name='attributes',
            name='MasterAttribute',
        ),
        migrations.RemoveField(
            model_name='attributes',
            name='RefAttrTableName',
        ),
        migrations.RemoveField(
            model_name='attributes',
            name='RefTableName',
        ),
        migrations.RemoveField(
            model_name='attributes',
            name='SelectedField',
        ),
        migrations.RemoveField(
            model_name='attributes',
            name='TableName',
        ),
        migrations.RemoveField(
            model_name='attributes',
            name='ValueField',
        ),
        migrations.RemoveField(
            model_name='attributes',
            name='ValueLeftOuter',
        ),
    ]
