# Generated by Django 3.1.2 on 2021-03-23 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ut', '0043_auto_20210219_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Template', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='reports',
            name='ViewGroups',
            field=models.ManyToManyField(blank=True, related_name='_reports_ViewGroups_+', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='classes',
            name='DefaultTemplate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ut.templates'),
        ),
        migrations.AlterField(
            model_name='sendouts',
            name='EmailTemplate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ut.templates'),
        ),
    ]
