# Generated by Django 3.1.2 on 2021-03-24 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0044_auto_20210322_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='DefaultTemplate',
        ),
        migrations.RemoveField(
            model_name='sendouts',
            name='EmailTemplate',
        ),
        migrations.DeleteModel(
            name='Templates',
        ),
    ]
