# Generated by Django 3.1.2 on 2021-03-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0045_auto_20210323_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TemplateName', models.CharField(max_length=100, unique=True)),
                ('Template', models.TextField()),
            ],
        ),
    ]
