# Generated by Django 3.1.2 on 2021-03-24 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0046_emailtemplates'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='DefaultEmailTemplate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ut.emailtemplates'),
        ),
        migrations.AddField(
            model_name='sendouts',
            name='EmailTemplate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ut.emailtemplates'),
        ),
    ]
