# Generated by Django 3.1.2 on 2021-03-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0047_auto_20210323_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplates',
            name='CcTemplate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplates',
            name='SubjectTemplate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplates',
            name='ToTemplate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
