# Generated by Django 3.1.2 on 2021-03-28 17:07

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0048_auto_20210327_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplates',
            name='Template',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
